### ISSUE TITLE
Cannot update to 2.3.3

### ISSUE THREAD

**Issue by edubecks** [dmarmor/epichrome#254]
Wheen I launch my app (youtube). I'm getting 

`A new version of Epichrome was found (2.3.3). This app is using version 2.3.2. Would you like to update it?`

Then I click in `Update` and get the following message: 

`Unable to complete update. (Unable to populate app bundle.) Please try update again later.`

Any clue?
The app launches normally with 2.3.2

**Comment by dmarmor** [comment]
That's not good! Could you send me a zip of the app in question, and a zip of the `Logs` directory (`~/Library/Application Support/Epichrome/Apps/<AppID>/Logs`) to this file request?

https://www.dropbox.com/request/iqKOe4ABCXzb90ng9ZkR

Thanks!

**Comment by dmarmor** [comment]
Thanks for sending the app. It updated to 2.3.3 with no problem on my system. Can you try another update to 2.3.3 (or 2.3.4, which I just released), and if it fails again, then zip up the `Logs` directory (as outline in my last comment) and send that to the same file request?

**Comment by edubecks** [comment]
I have uploaded the logs to dropbox. After updating to 2.3.4 I'm still getting the same error.

**Comment by dmarmor** [comment]
Hi @edubecks, thanks for sending the logs. Would I be correct in guessing that you had uploaded this app (or a zip thereof) and then downloaded it to yourself (or basically that you aren't running it on the same system where you created it)?

What appears to be going on is that Gatekeeper has quarantined the app, and thus when it runs, it get translocated to a virtual DMG, which is read-only. Because of that, the update can't work. The simplest solution would be to make sure the app is _not_ running, and then run this command on it:

```bash
xattr -cr <App Name>.app
```

Or, if you want to be more cautious:

```bash
xattr -d com.apple.quarantine <App Name>.app
```

Could you give that a try and then try the update again and let me know how it goes?

**Comment by edubecks** [comment]
thanks!!!

this worked, I copied it from my macbook. On top of what you said, one of the apps I created successfully updated to 2.3.3 without any issue 🤔 

in any case, this worked

**Comment by dmarmor** [comment]
Excellent! Glad that fixed it.
