### ISSUE TITLE
Icon missing after self-update (but fixed after 2nd restart)

### ISSUE THREAD

**Issue by trak3r** [dmarmor/epichrome#49]
After Epichrome detects a Chrome update and updates itself, it shows a broken icon in the dock and tab menu.
Restarting the app (again) restores the correct icon.
Just a minor annoyance to have to restart all your SSB's twice with each update.

**Comment by dmarmor** [comment]
Hi @trak3r, thanks for the report! I had noticed this too and have implemented a fix, but it didn't seem important enough to push out a new release right away. It'll be fixed in the next release.

**Comment by dmarmor** [comment]
Hey @trak3r, I just went ahead and published 2.1.9. Probably irrelevant now, since I'm guessing all your apps are already updated, but it should solve the problem going forward. Thanks again for the report!

**Comment by trak3r** [comment]
I installed the new version and opened an old app. Unfortunately it seemed to Chrome-update itself before it Epichrome-updated itself so couldn't verify this is fixed (although the correct icon did appear after both updates). But I'll assume so and report back here if I see the issue again. Thanks for all your work on this project @dmarmor

**Comment by dmarmor** [comment]
Sounds like it's working fine. Doing the Chrome update wouldn't affect the problem that was causing the wrong icon to appear. Thanks for the report, and I'm glad you're finding the project useful!

**Comment by wizonesolutions** [comment]
@dmarmor I'm noticing that I still see the ChromeEngine icon after a Chrome-only (but not Epichrome) update. This fixed the case where an update of both at once caused the ChromeEngine icon to appear.
