### ISSUE TITLE
Broken after newest Chrome Update

### ISSUE THREAD

**Issue by thenanyu** [dmarmor/epichrome#62]
On startup, the app icon for epichrome apps hang in the bouncing state.

**Comment by maxvoltar** [comment]
Yep.

**Comment by treyharris** [comment]
@thenanyu, @maxvoltar what "newest Chrome Update" please? (See chrome://version.) I'm on 49.0.2623.110 but my sandwich bar menu shows an update is waiting, so I'll be careful not to do it until this is rectified!

**Comment by treyharris** [comment]
I've just had issue #63 popup in trying to create a new SSB. It might be unrelated since I haven't updated Chrome in a few days, or it might not be, but since it's new behavior that just happened I thought I should raise it in case.

**Comment by thenanyu** [comment]
My Chrome version is 49.0.2623.112

As a side note, my issues were resolved after I restarted my computer (because of an OS update). If you haven't tried a system restart, maybe give that a shot if you are running into this problem.

**Comment by dmarmor** [comment]
Anybody still experiencing this with 49.0.2623.112, or did the reboot fix it? It runs fine on my system (OSX 10.11.4).

**Comment by dmarmor** [comment]
Anybody still experiencing this? I'll close for now, but feel free to reopen if it recurs...
